### ISSUE TITLE
The prediction is too slow (about ~3s/ text)

### ISSUE THREAD

**Issue by tarudesu** [unitaryai/detoxify#11]
Hi,
Firstly, so thank you guys for this repo. It's so helpful for us. 
I just used it for predicting texts in my dataset, but the speed is too slow. About 3 seconds per text. I wonder if it could be faster? 

Looking forward to hearing from you soon.
Regards,
Luan

**Comment by laurahanu** [comment]
Hi Luan,

Glad to hear you find it useful!

You should get something like ~0.02s per text on a GPU or ~0.03s on CPU using a single text input. 

Make sure not to initialise the model each time i.e. instead of calling `Detoxify('original').predict('example text')` every time, you should assign the model to a variable first `model = Detoxify('original')` and then call `model.predict('example text')`.

You can also increase the speed by batching text e.g. `model.predict(['example text 1', 'example text 2'])`. For example, with a batch of 30 you should get something like:
- On GPU: ~0.001s per text
- On CPU: ~0.004s per text

These numbers will vary based on the length of your inputs, with the longer the text, the more time it will take to process it.

Hope this helps!
